[package]
name = "bevy-lab"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }

[[example]]
name = "basic-lab-001-ecs"
path = "examples/basic/lab-001-ecs.rs"

[[example]]
name = "basic-lab-002-app-world"
path = "examples/basic/lab-002-app-world.rs"

[[example]]
name = "basic-lab-003-system"
path = "examples/basic/lab-003-system.rs"

[[example]]
name = "basic-lab-004-schedule"
path = "examples/basic/lab-004-schedule.rs"

[[example]]
name = "basic-lab-005-commands"
path = "examples/basic/lab-005-commands.rs"

[[example]]
name = "basic-lab-006-query"
path = "examples/basic/lab-006-query.rs"
