[package]
name = "bevy-lab"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main", features = ["bevy_feathers"] }

[[example]]
name = "basic-lab-001-ecs"
path = "examples/basic/lab-001-ecs.rs"

[[example]]
name = "basic-lab-002-app-world"
path = "examples/basic/lab-002-app-world.rs"

[[example]]
name = "basic-lab-003-system"
path = "examples/basic/lab-003-system.rs"

[[example]]
name = "basic-lab-004-schedule"
path = "examples/basic/lab-004-schedule.rs"

[[example]]
name = "basic-lab-005-commands"
path = "examples/basic/lab-005-commands.rs"

[[example]]
name = "basic-lab-006-query"
path = "examples/basic/lab-006-query.rs"

[[example]]
name = "basic-lab-007-resource"
path = "examples/basic/lab-007-resource.rs"

[[example]]
name = "basic-lab-008-state"
path = "examples/basic/lab-008-state.rs"

[[example]]
name = "basic-lab-009-message"
path = "examples/basic/lab-009-message.rs"

[[example]]
name = "basic-lab-010-run-if"
path = "examples/basic/lab-010-run-if.rs"

[[example]]
name = "basic-lab-011-time"
path = "examples/basic/lab-011-time.rs"

[[example]]
name = "basic-lab-012-timer"
path = "examples/basic/lab-012-timer.rs"

[[example]]
name = "basic-lab-013-plugin"
path = "examples/basic/lab-013-plugin.rs"

[[example]]
name = "basic-lab-014-bundle"
path = "examples/basic/lab-014-bundle.rs"

[[example]]
name = "basic-lab-015-observer"
path = "examples/basic/lab-015-observer.rs"

[[example]]
name = "basic-lab-016-local-system-state"
path = "examples/basic/lab-016-local-system-state.rs"

[[example]]
name = "basic-lab-017-default-resources-messages"
path = "examples/basic/lab-017-default-resources-messages.rs"

[[example]]
name = "input-lab-001-keyboard"
path = "examples/input/lab-001-keyboard.rs"

[[example]]
name = "input-lab-002-mouse"
path = "examples/input/lab-002-mouse.rs"

[[example]]
name = "input-lab-003-gamepad"
path = "examples/input/lab-003-gamepad.rs"

[[example]]
name = "input-lab-004-touch"
path = "examples/input/lab-004-touch.rs"

[[example]]
name = "ui-lab-001-ui-basics"
path = "examples/ui/lab-001-ui-basics.rs"

[[example]]
name = "ui-lab-002-node-properties"
path = "examples/ui/lab-002-node-properties.rs"

[[example]]
name = "ui-lab-003-node-visuals"
path = "examples/ui/lab-003-node-visuals.rs"

[[example]]
name = "ui-lab-004-events"
path = "examples/ui/lab-004-events.rs"

[[example]]
name = "ui-lab-005-common-widgets"
path = "examples/ui/lab-005-common-widgets.rs"

[[example]]
name = "ui-lab-006-bsn"
path = "examples/ui/lab-006-bsn.rs"

[[example]]
name = "ui-lab-007-feathers"
path = "examples/ui/lab-007-feathers.rs"
